###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Alvey, CS165
# Author:
#     Sergio Henrique
# Summary:
#     Having product lists and a way to compute shipping and total costs from
#     my last project has immensely helped my growing on-line business, but
#     to benefit even more from that program, I needed to add customers.
#     Builded on my Product library from last week, and created classes
#			to manage orders and customers as well.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp
